# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    - name: build and push docker image 
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: protech/123
        tags: v1, latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
        runs-on: ubuntu-latest

        steps:
          - name: SSH and deploy node app
            uses: appleboy/ssh-action@master
        with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          ssh -o StrictHostKeyChecking=no ubuntu@18.191.130.88 docker rm -f tanvicontainer || true
          ssh -o StrictHostKeyChecking=no ubuntu@18.191.130.88 docker run -d -p 3000:8083 --name tanvicontainergitactions tanvisable/123
          
          npm install --production
          pm2 restart node-app

        
        
        
      
