--- 
jobs: 
  build: 
    runs-on: ubuntu-latest
    steps: 
      - 
        uses: actions/checkout@v2
      - 
        name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v2
        with: 
          cache: npm
          node-version: "${{ matrix.node-version }}"
      - 
        run: "npm install"
      - 
        run: "npm run development"
      - 
        name: "Set up QEMU"
        uses: docker/setup-qemu-action@v1
      - 
        name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1
      - 
        name: "Login to DockerHub"
        uses: docker/login-action@v1
        with: 
          password: "${{ secrets.DOCKERHUB_TOKEN }}"
          username: "${{ secrets.DOCKERHUB_USERNAME }}"
      - 
        name: "Build and push"
        uses: docker/build-push-action@v2
        with: 
          context: ./
          file: ./Dockerfile
          push: true
          tags: "${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo:latest"
      - 
        name: "Run the image in a container"
        uses: addnab/docker-run-action@v3
        with: 
          image: "${{ secrets.DOCKERHUB_USERNAME }}/nodejs-demo:latest"
          run: |-
              echo "runing the docker image"
              echo "Testing the nodejs  app endpoints"
              echo ${{ steps.docker_build.outputs.digest }}
    strategy: 
      matrix: 
        node-version: 
          - 12.x
          - 14.x
          - 16.x
name: "Node.js CI"
true: 
  pull_request: 
    branches: 
      - second-edition
  push: 
    branches: 
      - second-edition
