# This is a basic workflow to help you get started with Actions
on: push
name: npmbuild,test

# Controls when the action will run. 

jobs:
  # This workflow contains multiple jobs
  build-and-publish:
    name: Build & publish
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@master
      - name: npm install
        uses: actions/npm@master
         with:
            args :install
            
      - name: Install dependencies
        run: |
          npm install
          npm ci 
      # build and test the apps     
      - name: build & test
        run: |
          npm run build
          npm run test
  push_to_Docker_Hub:
      name: Push Images to DockerHub
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      # build docker image and push to docker hub
      # only if the app build and test successfully
      needs: [build_test]

      steps:
        - name: checkout repo
          uses: actions/checkout@v2

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v1
      
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v1

        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
      
        - name: Build and push
          uses: docker/build-push-action@v2
          with:
            context: ./
            file: ./Dockerfile
            push: true
            tags: nodejs-demo:latest
          
        - name: Run the image in a container
          uses: addnab/docker-run-action@v3
          with:
            image: nodejs-demo:latest
            run: |
              echo "runing the docker image"
              echo "Testing the nodejs  app endpoints"
              echo ${{ steps.docker_build.outputs.digest }}

